const students = [
  {
    id: "S001",
    studyHours: 5,
    attendance: 85,
    assignmentScore: 78,
    finalMarks: 80,
    result: "Pass",
  },
  {
    id: "S002",
    studyHours: 2,
    attendance: 65,
    assignmentScore: 55,
    finalMarks: 48,
    result: "Fail",
  },
  {
    id: "S003",
    studyHours: 7,
    attendance: 92,
    assignmentScore: 88,
    finalMarks: 91,
    result: "Pass",
  },
  {
    id: "S004",
    studyHours: 3,
    attendance: 70,
    assignmentScore: 60,
    finalMarks: 55,
    result: "Pass",
  },
  {
    id: "S005",
    studyHours: 1,
    attendance: 50,
    assignmentScore: 40,
    finalMarks: 35,
    result: "Fail",
  },
  {
    id: "S006",
    studyHours: 6,
    attendance: 88,
    assignmentScore: 82,
    finalMarks: 85,
    result: "Pass",
  },
  {
    id: "S007",
    studyHours: 2,
    attendance: 60,
    assignmentScore: 50,
    finalMarks: 42,
    result: "Fail",
  },
  {
    id: "S008",
    studyHours: 8,
    attendance: 95,
    assignmentScore: 90,
    finalMarks: 94,
    result: "Pass",
  },
  {
    id: "S009",
    studyHours: 4,
    attendance: 75,
    assignmentScore: 70,
    finalMarks: 68,
    result: "Pass",
  },
  {
    id: "S010",
    studyHours: 1,
    attendance: 45,
    assignmentScore: 35,
    finalMarks: 30,
    result: "Fail",
  },
  {
    id: "S011",
    studyHours: 5,
    attendance: 82,
    assignmentScore: 76,
    finalMarks: 78,
    result: "Pass",
  },
  {
    id: "S012",
    studyHours: 3,
    attendance: 68,
    assignmentScore: 58,
    finalMarks: 51,
    result: "Pass",
  },
  {
    id: "S013",
    studyHours: 7,
    attendance: 90,
    assignmentScore: 85,
    finalMarks: 89,
    result: "Pass",
  },
  {
    id: "S014",
    studyHours: 2,
    attendance: 55,
    assignmentScore: 45,
    finalMarks: 40,
    result: "Fail",
  },
  {
    id: "S015",
    studyHours: 6,
    attendance: 86,
    assignmentScore: 80,
    finalMarks: 83,
    result: "Pass",
  },
];

export default students;